name: hv-lueneburg
app_id: da_K53IxtPUDEmo
owner: krustyxkrab
package: '.'
capabilities:
  database:
    engine: mysql
volumes:
- name: uploads
  mount: /app/wp-content/uploads
scaling:
  mode: single_concurrency
kind: wasmer.io/App.v0
